from fpdf import FPDF
import os

class PDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, "Desi Tracker - Mobile App vs Website Analysis", 0, 0, "L")
        self.cell(0, 8, "Page " + str(self.page_no()), 0, 1, "R")
        self.line(10, 18, 200, 18)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by Desi Tracker Analysis", 0, 0, "C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, title, 0, 1, "L")
        self.set_draw_color(0, 51, 102)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def sub_title(self, title):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(51, 51, 51)
        self.cell(0, 8, title, 0, 1, "L")
        self.ln(2)

    def body_text(self, text):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def bullet(self, text, indent=15):
        start_x = self.get_x()
        self.set_x(start_x + indent)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 5, "- " + text)
        self.ln(1)

    def bullet_bold(self, bold_part, text, indent=15):
        start_x = self.get_x()
        self.set_x(start_x + indent)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 5, bold_part + " " + text)
        self.ln(1)

    def status_badge(self, status, text):
        if status == "critical":
            self.set_fill_color(220, 53, 69)
            self.set_text_color(255, 255, 255)
        elif status == "missing":
            self.set_fill_color(255, 193, 7)
            self.set_text_color(0, 0, 0)
        elif status == "partial":
            self.set_fill_color(255, 165, 0)
            self.set_text_color(0, 0, 0)
        elif status == "working":
            self.set_fill_color(40, 167, 69)
            self.set_text_color(255, 255, 255)
        else:
            self.set_fill_color(108, 117, 125)
            self.set_text_color(255, 255, 255)
        
        self.set_font("Helvetica", "B", 7)
        w = self.get_string_width(status.upper()) + 4
        self.cell(w, 5, status.upper(), 0, 0, "C", True)
        self.ln(1)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 5, "  " + text)
        self.ln(1)

    def table_header(self, headers, col_widths):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(0, 51, 102)
        self.set_text_color(255, 255, 255)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, h, 1, 0, "C", True)
        self.ln()

    def table_row(self, cells, col_widths, fill=False):
        self.set_font("Helvetica", "", 8)
        if fill:
            self.set_fill_color(240, 240, 245)
        else:
            self.set_fill_color(255, 255, 255)
        self.set_text_color(51, 51, 51)
        for i, c in enumerate(cells):
            self.cell(col_widths[i], 6, c, 1, 0, "L", fill)
        self.ln()

pdf = PDF()
pdf.set_auto_page_break(auto=True, margin=20)

# ============ COVER PAGE ============
pdf.add_page()
pdf.ln(40)
pdf.set_font("Helvetica", "B", 32)
pdf.set_text_color(0, 51, 102)
pdf.cell(0, 15, "Desi Tracker", 0, 1, "C")
pdf.set_font("Helvetica", "", 18)
pdf.set_text_color(100, 100, 100)
pdf.cell(0, 12, "Mobile App vs Website", 0, 1, "C")
pdf.cell(0, 12, "Complete Feature Analysis", 0, 1, "C")
pdf.ln(15)
pdf.set_draw_color(0, 51, 102)
pdf.line(60, pdf.get_y(), 150, pdf.get_y())
pdf.ln(15)
pdf.set_font("Helvetica", "", 12)
pdf.set_text_color(80, 80, 80)
pdf.cell(0, 8, "Project: Desi Tracker", 0, 1, "C")
pdf.cell(0, 8, "Report: Full Feature Comparison & Gap Analysis", 0, 1, "C")
pdf.cell(0, 8, "Date: May 2026", 0, 1, "C")
pdf.ln(10)
pdf.set_font("Helvetica", "B", 14)
pdf.set_text_color(0, 51, 102)
pdf.cell(0, 8, "Overall Completion: ~60%", 0, 1, "C")

# ============ TABLE OF CONTENTS ============
pdf.add_page()
pdf.section_title("Table of Contents")
pdf.ln(5)
toc = [
    "1. Project Overview",
    "2. Tech Stack Comparison",
    "3. Authentication Feature Comparison",
    "4. Business Registration Feature Comparison",
    "5. Order Pad Feature Comparison",
    "6. Critical Issues (Broken / Stubs)",
    "7. Missing Features (Website has, App doesn't)",
    "8. Partial Features (Incomplete in App)",
    "9. Working Features (Both have)",
    "10. Full Screen Inventory",
    "11. Backend API Analysis",
    "12. Security Gaps",
    "13. Dead Code in App",
    "14. Summary & Recommendations",
]
for item in toc:
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(51, 51, 51)
    pdf.cell(0, 8, item, 0, 1)

# ============ 1. PROJECT OVERVIEW ============
pdf.add_page()
pdf.section_title("1. Project Overview")
pdf.body_text("Desi Tracker is a business directory and management platform with three main components:")
pdf.bullet_bold("Backend:", "Node.js/Express/MongoDB API serving both web and mobile")
pdf.bullet_bold("Website:", "Next.js 15 (App Router) / React 19 / TypeScript web application")
pdf.bullet_bold("Mobile App:", "Expo SDK 54 / React Native 0.81 / JavaScript mobile application")
pdf.ln(3)
pdf.body_text("The platform supports three user types: Business Owners, Members (QR-card loyalty), and Admins. Key features include business listing, product management, order taking (POS), member verification, reviews, bookings, rota management, and fridge temperature logging.")

# ============ 2. TECH STACK ============
pdf.add_page()
pdf.section_title("2. Tech Stack Comparison")
pdf.ln(2)

headers = ["Component", "Backend", "Website", "Mobile App"]
widths = [35, 55, 55, 45]
pdf.table_header(headers, widths)

rows = [
    ["Language", "TypeScript 5.7", "TypeScript", "JavaScript"],
    ["Framework", "Express 4.21", "Next.js 15.2", "Expo SDK 54"],
    ["UI Library", "N/A", "React 19", "React Native 0.81"],
    ["Database", "MongoDB/Mongoose 8", "N/A (API client)", "N/A (API client)"],
    ["State Mgmt", "N/A", "Redux Toolkit + RTK Query", "Redux + RTK Query + Axios"],
    ["Forms", "Mongoose validators", "react-hook-form", "Manual state + Alerts"],
    ["Styling", "N/A", "Tailwind CSS 4.1", "StyleSheet (inline)"],
    ["Navigation", "Express Router", "Next.js App Router", "React Navigation v6"],
    ["Notifications", "N/A", "react-hot-toast", "Native Alert dialogs"],
    ["Icons", "N/A", "react-icons", "lucide-react-native"],
    ["Token Storage", "httpOnly cookie", "js-cookie (browser)", "AsyncStorage (insecure)"],
    ["Deployment", "Vercel", "Vercel", "Expo (managed)"],
]
for i, row in enumerate(rows):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

# ============ 3. AUTH COMPARISON ============
pdf.add_page()
pdf.section_title("3. Authentication Feature Comparison")

pdf.sub_title("Backend Auth System")
pdf.body_text("Two independent auth systems:")
pdf.bullet_bold("User Auth:", "For website users, admins, business owners. JWT 10-day expiry, bcrypt 12 rounds, httpOnly cookie")
pdf.bullet_bold("Member Auth:", "For QR-card loyalty members. Phone+password login, bcryptjs 10 rounds, 7-day JWT")
pdf.ln(2)

pdf.sub_title("Login Flow Comparison")
headers = ["Feature", "Website", "Mobile App"]
widths = [50, 65, 75]
pdf.table_header(headers, widths)

auth_rows = [
    ["Email/Phone login", "Yes - single input", "Yes - single input"],
    ["Password show/hide", "Yes", "Yes"],
    ["Auto-login after register", "Yes", "Yes"],
    ["Token storage", "Cookie (js-cookie)", "AsyncStorage"],
    ["JWT decode", "jwt-decode library", "Manual base64"],
    ["Role-based redirect", "Yes", "Yes"],
    ["Forgot password", "RTK Query endpoint", "RTK Query endpoint"],
    ["Reset password", "RTK Query endpoint", "Raw fetch (hardcoded URL)"],
    ["Logout API call", "Yes - POST /auth/logout", "No - just clears local"],
    ["Member fallback login", "Separate page", "Same screen fallback"],
]
for i, row in enumerate(auth_rows):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

pdf.ln(5)
pdf.sub_title("Route Protection")
pdf.bullet_bold("Website:", "3 guard components + server-side cookie check + role-based admin guard")
pdf.bullet_bold("App:", "No formal guards. All screens accessible. ProfileScreen checks token on focus only.")

# ============ 4. BUSINESS REGISTRATION ============
pdf.add_page()
pdf.section_title("4. Business Registration Feature Comparison")
pdf.body_text("When a business uploads or registers, the website has 21 feature areas. Here is the comparison:")
pdf.ln(2)

headers = ["Feature", "Website", "App Register", "App Edit"]
widths = [45, 35, 50, 60]
pdf.table_header(headers, widths)

biz_rows = [
    ["1. Business Name", "Yes", "Yes", "Yes"],
    ["2. Category", "API dropdown", "API chips", "API chips"],
    ["   Subcategory", "API dropdown", "MISSING", "State exists, no UI"],
    ["3. Description", "Textarea", "Multiline input", "Yes"],
    ["4. Facebook", "Yes", "MISSING", "Yes"],
    ["   Website", "Yes", "Yes", "Yes"],
    ["   LinkedIn", "Yes", "MISSING", "MISSING"],
    ["   Twitter", "Yes", "MISSING", "MISSING"],
    ["   Instagram", "Yes", "MISSING", "Yes"],
    ["5. Opening Hours", "Toggle + time pickers", "Hardcoded default", "Toggle only"],
    ["6. Operational Period", "Label (no actual)", "MISSING", "MISSING"],
    ["7. Halal Service", "Toggle", "Toggle", "Toggle"],
    ["8. Home Delivery", "Toggle", "Toggle", "Toggle"],
    ["9. Online Service", "Toggle + link input", "MISSING", "MISSING"],
    ["10. In-Store Pickup", "Toggle", "MISSING", "MISSING"],
    ["11. Parking", "Toggle", "Toggle", "Toggle"],
    ["12. Table Reservation", "Conditional toggle", "MISSING", "MISSING"],
    ["13. Special Discount", "Toggle", "Hardcoded false", "MISSING"],
    ["14. Wheelchair", "Toggle", "Hardcoded false", "MISSING"],
    ["15. Payment Methods", "9-option multi-select", "Empty array", "Empty array"],
    ["16. Address", "Yes", "Yes", "Yes"],
    ["   Country", "Dropdown", "Free text", "Free text"],
    ["   Post Code", "Yes", "Yes", "Yes"],
    ["   City", "Dropdown", "Free text", "Free text"],
    ["   Multiple Locations", "Yes + sub-branches", "Hardcoded false", "MISSING"],
    ["17. Language", "99-lang dropdown", "Free text", "MISSING"],
    ["18. Business Logo", "Upload + preview", "ImagePicker", "ImagePicker+camera"],
    ["19. Gallery Images", "Multi-upload + thumb", "MISSING", "MISSING"],
    ["20. Video Upload", "Video upload", "MISSING", "MISSING"],
    ["21. Terms & Conditions", "Checkbox", "Toggle", "MISSING"],
]
for i, row in enumerate(biz_rows):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

pdf.ln(3)
pdf.body_text("Category/Subcategory source: Fetched from API (GET /api/v1/category), NOT hardcoded.")

# ============ 5. ORDER PAD ============
pdf.add_page()
pdf.section_title("5. Order Pad Feature Comparison")

pdf.sub_title("Backend Order Schema")
pdf.body_text("Order model stores: business_id, user_id, tableNo, notes, items[] (with lineId, productId, name, price, quantity, selectedOptions), totalQty, subtotal, membershipDiscount, currency, status (pending/completed/cancelled). No auth on any order endpoint.")
pdf.ln(2)

pdf.sub_title("Order Pad Comparison")
headers = ["Feature", "Website", "Mobile App", "Backend"]
widths = [40, 50, 50, 50]
pdf.table_header(headers, widths)

order_rows = [
    ["Order pad UI", "Full (1316 lines)", "Full (732 lines)", "N/A"],
    ["Restaurant-only gating", "Yes (regex check)", "NO - shown to ALL", "N/A"],
    ["Product categories", "API fetch", "API fetch", "Product model"],
    ["Product options/variants", "Modal picker", "Modal picker", "selectedOptions[]"],
    ["Table number", "Input field", "Input field", "tableNo field"],
    ["Notes", "Textarea", "Textarea", "notes field"],
    ["Membership discount", "Serial lookup", "Serial lookup", "membershipDiscount{}"],
    ["Order list", "With filters", "With status", "listOrders endpoint"],
    ["Edit order", "Full", "Full", "updateOrder endpoint"],
    ["Receipt/PDF", "Print page works", "Screen exists, unreachable", "N/A"],
    ["Customer cart checkout", "WhatsApp only", "STUB (Alert only)", "No payment module"],
    ["Order status", "3 states", "4 states (+preparing)", "3 states"],
    ["Real-time updates", "No", "No", "No WebSocket"],
    ["Kitchen display", "No", "No", "No"],
    ["Payment integration", "No", "No", "No"],
    ["Split bills", "No", "No", "No"],
]
for i, row in enumerate(order_rows):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

# ============ 6. CRITICAL ISSUES ============
pdf.add_page()
pdf.section_title("6. Critical Issues - Broken / Stubs in App")

pdf.set_font("Helvetica", "B", 9)
pdf.set_text_color(220, 53, 69)
pdf.cell(0, 7, "These features exist in the app but are broken or incomplete:", 0, 1)
pdf.ln(3)

pdf.set_font("Helvetica", "", 9)
pdf.set_text_color(51, 51, 51)

issues = [
    ["Cart checkout is a stub", "Alert.alert('Checkout flow coming soon') - no order creation or payment"],
    ["GenerateReceiptScreen unreachable", "Screen exists and is registered but nothing navigates to it with proper params"],
    ["Reset password uses raw fetch", "Hardcoded URL bypasses API layer, no error handling, ignores app.json config"],
    ["Favorites are device-only", "AsyncStorage only - lost on reinstall, not synced to backend for logged-in users"],
    ["Business offers screen has mock data", "Hardcoded data with zero API/backend integration"],
    ["Business promote screen has mock data", "Hardcoded data with zero API/backend integration"],
    ["Member dashboard visit history is stub", "Returns Promise.resolve({ data: [] }) - no real API call"],
    ["PDF receipt in order list is stub", "Shows Alert instead of navigating to GenerateReceiptScreen"],
    ["Order list uses old axios, not RTK Query", "listOrders RTK Query defined but never imported or used"],
    ["ChangePassword calls wrong endpoint", "Sends JWT to reset-password endpoint instead of update-password"],
    ["Logout doesn't call API", "Just clears AsyncStorage, never calls POST /auth/logout"],
    ["No restaurant category gating", "Order pad shown to ALL business types, not just restaurants"],
]

for title, desc in issues:
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(220, 53, 69)
    pdf.cell(5, 5, "")
    pdf.cell(0, 5, title, 0, 1)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(10, 5, "")
    pdf.multi_cell(0, 5, desc)
    pdf.ln(2)

# ============ 7. MISSING FEATURES ============
pdf.add_page()
pdf.section_title("7. Missing Features - Website Has, App Doesn't")

pdf.ln(2)
headers = ["Feature", "Website", "App"]
widths = [55, 65, 70]
pdf.table_header(headers, widths)

missing_rows = [
    ["Restaurant-only gating (isRestaurant check)", "Hides order pad from non-restaurants", "Order pad shown to ALL businesses"],
    ["QR code view/download (member)", "Full member QR code tab", "Not in app"],
    ["Member deactivation requests", "Submit + view history", "Not in app"],
    ["Day offers management", "Create/list/apply day-of-week offers", "Not in app"],
    ["Bulk product discount", "Apply discount to multiple products with date range", "Not in app"],
    ["Product options CRUD", "Create/edit option groups (size, spice, etc.)", "Not in app"],
    ["Leads management", "Add/remove members as leads, send promotions", "Not in app"],
    ["Business analytics", "Visitor count + monthly breakdown", "Not in app"],
    ["Member verification (QR scan)", "Verify by slug/serial", "Not in app"],
    ["Restaurant offers browse", "Filter by country/city/discount", "Not in app"],
    ["Contact us form", "Sends message via API", "Not in app"],
    ["How it works page", "Explainer page", "Not in app"],
    ["Site testimonials", "Public testimonials", "Not in app"],
    ["Sub-branch/multiple locations", "Full branch system", "Hardcoded false"],
    ["User dashboard", "Has route (empty placeholder)", "Not in app"],
    ["Product management in app", "Full CRUD with discount + date window", "Partial - basic CRUD only"],
]
for i, row in enumerate(missing_rows):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

# ============ 8. PARTIAL FEATURES ============
pdf.add_page()
pdf.section_title("8. Partial Features - Incomplete in App")

pdf.ln(2)
headers = ["Feature", "Website (Full)", "App (Partial)"]
widths = [50, 65, 75]
pdf.table_header(headers, widths)

partial_rows = [
    ["Opening hours", "Toggle + time pickers (30-min increments)", "Toggle only, no time editing"],
    ["Country/City selection", "Dropdowns with data files", "Free text inputs"],
    ["Language selection", "99-language dropdown", "Free text / hardcoded 'English'"],
    ["Gallery images", "Multi-upload + thumbnail selection", "Logo only, no gallery"],
    ["Video upload", "Video upload component", "Missing entirely"],
    ["Payment methods", "9-option multi-select dropdown", "Hardcoded empty array"],
    ["Social media fields", "All 5: FB, IG, LinkedIn, Twitter, Website", "Only Website (+ FB/IG in Edit only)"],
    ["Edit business form", "Full form with all 21 fields", "Missing 12+ fields"],
    ["API layer consistency", "RTK Query only", "Dual layers: RTK Query + legacy axios"],
    ["Token security", "httpOnly cookie (backend-set)", "AsyncStorage (JS-readable, insecure)"],
    ["Error display", "Inline + toast (non-blocking)", "Native Alert dialogs (blocking)"],
    ["Form validation", "react-hook-form with inline errors", "Manual pre-submit + Alert dialogs"],
]
for i, row in enumerate(partial_rows):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

# ============ 9. WORKING FEATURES ============
pdf.add_page()
pdf.section_title("9. Working Features - Both Website and App Have")

pdf.ln(2)
working = [
    "Authentication (login, register, forgot password)",
    "Home screen with featured businesses, banners, sliders",
    "Business search with filters (category, location, rating)",
    "Business list and detail pages",
    "Category browsing",
    "Product detail viewing",
    "Reviews (list + submit)",
    "My reviews",
    "Bookings (create + manage)",
    "My bookings",
    "Rota management (roles, employees, shifts)",
    "Fridge temperature logging",
    "Waiter order pad (core flow: browse, add, options, cart, submit)",
    "Order list with status updates",
    "Edit order (items, qty, status, notes)",
    "Profile edit",
    "Change password",
    "Settings",
    "About, Terms, Privacy, FAQ, Help pages",
    "Admin screens (banners, members, reviews, settings, sliders, testimonials)",
    "Notifications",
    "Member login and registration",
    "Cart (add/remove/quantity management)",
]

for item in working:
    pdf.bullet(item)

# ============ 10. FULL SCREEN INVENTORY ============
pdf.add_page()
pdf.section_title("10. Full Screen Inventory - Mobile App (62 screens)")

pdf.sub_title("Working (API-integrated, functional) - ~30 screens")
working_screens = [
    "LoginScreen - Token + role fetch",
    "RegisterScreen - Member/business registration",
    "ForgotPasswordScreen - Email-based reset request",
    "HomeScreen - Featured businesses, banners, sliders",
    "SearchScreen - Filter by category, location, rating",
    "BusinessDetailScreen - Full profile, reviews, location map",
    "BusinessListScreen - Paginated list with filters",
    "CategoryListScreen - Browse by category",
    "ProductDetailScreen - Product info, add to cart",
    "CartScreen - Local state only (no checkout)",
    "OrderHistoryScreen - Past orders for members",
    "OrderDetailScreen - Single order view",
    "ProfileScreen - User info, edit profile",
    "EditProfileScreen - Update user details",
    "ChangePasswordScreen - Password update",
    "ReviewsScreen - List + submit reviews",
    "MyReviewsScreen - User's own reviews",
    "BookingScreen - Create/manage bookings",
    "MyBookingsScreen - Booking history",
    "RotaScreen - Staff rota management",
    "FridgeScreen - Fridge/inventory management",
    "WaiterOrdersScreen - Waiter order queue",
    "NotificationScreen - Push/in-app notifications",
    "SettingsScreen - App settings, logout",
    "AboutScreen, ContactScreen, TermsScreen, PrivacyScreen, FAQScreen, HelpScreen - Static pages",
]
for s in working_screens:
    pdf.bullet(s)

pdf.ln(3)
pdf.sub_title("Stub / Incomplete - 5 screens")
stub_screens = [
    "BusinessOffersScreen - Hardcoded mock data, zero API integration",
    "BusinessPromoteScreen - Hardcoded mock data, zero API integration",
    "MemberDashboardScreen - Visit history returns empty array stub",
    "CartScreen - Checkout button is a stub (Alert only)",
    "FavoritesScreen - AsyncStorage only, no backend sync",
]
for s in stub_screens:
    pdf.bullet(s)

pdf.ln(3)
pdf.sub_title("Broken / Non-Standard - 3 screens")
broken_screens = [
    "ResetPasswordScreen - Raw fetch to hardcoded URL, bypasses API layer",
    "FavoritesScreen - Lost on app reinstall, not shared across devices",
    "GenerateReceiptScreen - Exists but unreachable (nothing navigates to it)",
]
for s in broken_screens:
    pdf.bullet(s)

# ============ 11. BACKEND API ============
pdf.add_page()
pdf.section_title("11. Backend API Analysis")

pdf.sub_title("User Auth Endpoints")
headers = ["Method", "Path", "Auth"]
widths = [20, 90, 80]
pdf.table_header(headers, widths)
auth_api = [
    ["POST", "/api/v1/users/register", "No (multer for file)"],
    ["POST", "/api/v1/auth/login", "No"],
    ["POST", "/api/v1/auth/logout", "No"],
    ["POST", "/api/v1/auth/forgot-password", "No"],
    ["POST", "/api/v1/auth/reset-password/:token", "No"],
    ["GET", "/api/v1/users/me", "Yes (any role)"],
    ["PUT", "/api/v1/users/:id", "Yes (any role)"],
    ["DELETE", "/api/v1/users/:id", "Yes (admin only)"],
]
for i, row in enumerate(auth_api):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

pdf.ln(3)
pdf.sub_title("Business Endpoints")
pdf.table_header(headers, widths)
biz_api = [
    ["POST", "/api/v1/business/register", "Yes (Admin/User/BusinessOwner)"],
    ["GET", "/api/v1/business", "Public"],
    ["GET", "/api/v1/business/list", "Public"],
    ["GET", "/api/v1/business/:slug", "Public"],
    ["PUT", "/api/v1/business/:slug", "Yes (Admin/BusinessOwner)"],
    ["DELETE", "/api/v1/business/:slug", "Yes (Admin/BusinessOwner)"],
]
for i, row in enumerate(biz_api):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

pdf.ln(3)
pdf.sub_title("Order Endpoints (NO AUTH on any)")
pdf.table_header(headers, widths)
order_api = [
    ["POST", "/orders/create", "No auth"],
    ["GET", "/orders?business_id=&user_id=&status=", "No auth"],
    ["GET", "/orders/:id?business_id=", "No auth"],
    ["PUT", "/orders/:id", "No auth"],
    ["DELETE", "/orders/:id?business_id=", "No auth"],
]
for i, row in enumerate(order_api):
    pdf.table_row(row, widths, fill=(i % 2 == 0))

pdf.ln(5)
pdf.body_text("Note: All order endpoints lack authentication. Tenant isolation relies only on business_id in queries.")

# ============ 12. SECURITY GAPS ============
pdf.add_page()
pdf.section_title("12. Security Gaps")

pdf.sub_title("Mobile App")
pdf.bullet("Token stored in AsyncStorage (insecure) - expo-secure-store is installed but NOT used")
pdf.bullet("Token is fully accessible via JavaScript at all times")
pdf.bullet("JWT decoded client-side without signature verification")
pdf.bullet("No token expiry checking - app never checks if token is expired")
pdf.bullet("No request retry on 401 - ProfileScreen clears token, other screens show generic error")
pdf.bullet("No refresh tokens - single access token only")
pdf.bullet("No CSRF protection")
pdf.bullet("ResetPasswordScreen bypasses API layer with raw fetch to hardcoded URL")
pdf.ln(2)

pdf.sub_title("Backend")
pdf.bullet("No rate limiting on any endpoint (login, register, password reset)")
pdf.bullet("No email verification on signup")
pdf.bullet("No refresh token rotation - refresh secret defined but never used")
pdf.bullet("All order endpoints have NO authentication")
pdf.bullet("Reset password uses same JWT secret as access token (should use separate secret)")
pdf.bullet("Phone number unique index is dropped on every registration (allows duplicates)")
pdf.bullet("No inventory/stock tracking for products")
pdf.bullet("No validation that referenced products exist when creating orders")

pdf.sub_title("Website")
pdf.bullet("Token in JS-readable cookie (no httpOnly flag on client side)")
pdf.bullet("No refresh token logic")
pdf.bullet("Client-side route guards can flash protected content before redirect")
pdf.bullet("Logout bug: removes 'accessToken' cookie instead of 'desiTrackerToken'")

# ============ 13. DEAD CODE ============
pdf.add_page()
pdf.section_title("13. Dead Code in Mobile App")

pdf.body_text("The app has significant unused code that adds complexity without providing value:")
pdf.ln(2)

pdf.bullet_bold("authSlice.js:", "Redux auth reducer is registered in the store but NEVER dispatched. setAuth is never called. isAuthenticated flag is never read by any component. All auth state flows through the Axios-layer getToken()/getRole().")
pdf.bullet_bold("authApi.js (RTK Query):", "Endpoints defined (registerUser, loginUser, logoutUser, forgotPassword, resetPassword) but only forgotPassword and resetPassword are used. The register/login RTK endpoints are NEVER consumed - the Axios layer is used instead.")
pdf.bullet_bold("memberApi.js (RTK Query):", "registerMember and loginMember mutations are never used. The Axios layer memberApi is used instead.")
pdf.bullet_bold("expo-secure-store:", "Installed as a dependency but NEVER used for auth token storage. Tokens are stored in insecure AsyncStorage.")
pdf.bullet_bold("listOrders RTK Query:", "Defined in ordersApi.js but never imported or used. BusinessOrdersScreen uses the older axios wrapper instead.")
pdf.bullet_bold("GenerateReceiptScreen:", "Registered in AppNavigator but nothing navigates to it with proper params. The screen is completely unreachable.")

# ============ 14. SUMMARY ============
pdf.add_page()
pdf.section_title("14. Summary & Recommendations")

pdf.sub_title("Overall Completion: ~60%")
pdf.body_text("The mobile app has a functional core (auth, business discovery, order pad, reviews, bookings, rota, fridge) but is missing critical business features and has several broken/stub implementations.")

pdf.ln(3)
pdf.sub_title("Priority 1 - Fix Broken Features")
pdf.bullet("Connect GenerateReceiptScreen to order list (PDF receipt download)")
pdf.bullet("Implement cart checkout flow (create order from customer cart)")
pdf.bullet("Fix ResetPasswordScreen to use RTK Query instead of raw fetch")
pdf.bullet("Sync favorites to backend for logged-in users")
pdf.bullet("Wire BusinessOffersScreen and BusinessPromoteScreen to real APIs")
pdf.bullet("Fix MemberDashboardScreen to call real visit history API")

pdf.ln(3)
pdf.sub_title("Priority 2 - Add Missing Features")
pdf.bullet("Add restaurant category gating (isRestaurant check) to hide order pad from non-restaurants")
pdf.bullet("Add QR code view/download for members")
pdf.bullet("Add member deactivation request flow")
pdf.bullet("Add day offers management")
pdf.bullet("Add leads management (add/remove/promote)")
pdf.bullet("Add business analytics (visitor count)")
pdf.bullet("Add member verification (QR scan)")
pdf.bullet("Add restaurant offers browse (filter by country/city/discount)")

pdf.ln(3)
pdf.sub_title("Priority 3 - Improve Partial Features")
pdf.bullet("Add time pickers to opening hours (not just toggle)")
pdf.bullet("Convert Country/City to dropdowns")
pdf.bullet("Add gallery image multi-upload and video upload")
pdf.bullet("Add payment methods multi-select")
pdf.bullet("Add all social media fields to registration")
pdf.bullet("Complete EditBusinessScreen with all fields")
pdf.bullet("Consolidate dual API layers (remove dead axios code)")

pdf.ln(3)
pdf.sub_title("Priority 4 - Security")
pdf.bullet("Move token storage from AsyncStorage to expo-secure-store")
pdf.bullet("Add token expiry checking")
pdf.bullet("Add 401 retry/refresh logic")
pdf.bullet("Add auth to order endpoints on backend")
pdf.bullet("Add rate limiting on backend auth endpoints")
pdf.bullet("Add email verification on signup")

# Save PDF
output_path = r"D:\deshi tracker\DesiTracker_Analysis_Report.pdf"
pdf.output(output_path)
print(f"PDF saved to: {output_path}")
print(f"File size: {os.path.getsize(output_path)} bytes")
